# Generated by Django 4.0.2 on 2022-12-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_video_file_alter_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video_file',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='product_files'),
        ),
    ]
