# Generated by Django 4.0.2 on 2022-12-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_video_file_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='fashion.jpg', upload_to='product_pics'),
        ),
    ]
