# Generated by Django 4.0.2 on 2022-12-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
