# Generated by Django 4.0.2 on 2022-12-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Physical Product'), (1, 'Digital Product')], default=0),
        ),
    ]
